version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "adyen-shop-checkout"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wd9fa2oxyv95"
s3_prefix = "adyen-shop-checkout"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
