AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  adyen-shop-checkout

  Sample SAM Template for adyen-shop-checkout

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
  Api:
    Cors:
      AllowOrigin: "'*'"
    Auth:
      ApiKeyRequired: false
  
Resources:
  PaymentMethodsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: payment-methods/
      Handler: appy.lambda_handler
      Runtime: python3.6
      Events:
        GetPaymentMethods:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /payment-methods
            Method: get  
        
  PaymentsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: payments/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        PostPayments:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /payments
            Method: post
  

Outputs:
  PaymentMethodsFunctionAPI:
    Description: "API Gateway endpoint URL for Prod stage for PaymentsMethod function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/payment-methods/"

  PaymentsFunctionAPI:
    Description: "API Gateway endpoint URL for Prod stage for PaymentsMethod function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/payments/"
