AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  adyen-shop-checkout

  Sample SAM Template for adyen-shop-checkout

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Auth:
      ApiKeyRequired: false
  
Resources:
  PaymentMethodsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: payment-methods/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        GetPaymentMethods:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /paymentmethods
            Method: get
            
  PaymentsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: payments/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        PostPayments:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /paynments
            Method: post
  

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PaymentMethodsFunctionAPI:
    Description: "API Gateway endpoint URL for Prod stage for PaymentsMethod function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/paymentmethods/"
  PaymentMethodsFunction:
    Description: "PaymentsMethod Lambda Function ARN"
    Value: !GetAtt PaymentMethodsFunction.Arn
  PaymentMethodsFunctionIAMRole:
    Description: "Implicit IAM Role created for PaymentsMethod function"
    Value: !GetAtt PaymentMethodsFunctionRole.Arn

  PaymentsFunctionAPI:
    Description: "API Gateway endpoint URL for Prod stage for PaymentsMethod function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/payments/"
  PaymentsFunction:
    Description: "PaymentsMethod Lambda Function ARN"
    Value: !GetAtt PaymentsFunction.Arn
  PaymentsFunctionIAMRole:
    Description: "Implicit IAM Role created for PaymentsMethod function"
    Value: !GetAtt PaymentsFunctionRole.Arn
